services:
  db:
    image: mysql:latest
    container_name: forum-db
    env_file:
      - .env
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - forum-network

  adminer:
    image: adminer
    container_name: forum-adminer
    ports:
      - "3307:8080"
    networks:
      - forum-network

networks:
  forum-network:
    driver: bridge
